### ISSUE TITLE
No output on display or in terminal 

### ISSUE THREAD

**Issue by timf34** [waveshare/UPS-Power-Module#4]
Hi,

I followed the instructions and have the following output when running ./install.sh and running the ina219 python file respectively. There is no output on the display for the former, and the python file runs an error

`sudo ./install.sh`

> Get:1 file:/var/cuda-repo-l4t-10-2-local  InRelease
Ign:1 file:/var/cuda-repo-l4t-10-2-local  InRelease
Get:2 file:/var/visionworks-repo  InRelease
Ign:2 file:/var/visionworks-repo  InRelease
Get:3 file:/var/visionworks-sfm-repo  InRelease
Ign:3 file:/var/visionworks-sfm-repo  InRelease      
Get:4 file:/var/visionworks-tracking-repo  InRelease              
Ign:4 file:/var/visionworks-tracking-repo  InRelease                                                       
Get:5 file:/var/cuda-repo-l4t-10-2-local  Release [564 B]                                                  
Get:6 file:/var/visionworks-repo  Release [2,001 B]                                                        
Get:7 file:/var/visionworks-sfm-repo  Release [2,005 B]                                                    
Get:5 file:/var/cuda-repo-l4t-10-2-local  Release [564 B]                                                  
Get:8 file:/var/visionworks-tracking-repo  Release [2,010 B]                                               
Get:6 file:/var/visionworks-repo  Release [2,001 B]                                                        
Get:7 file:/var/visionworks-sfm-repo  Release [2,005 B]                                                    
Get:8 file:/var/visionworks-tracking-repo  Release [2,010 B]                                               
Hit:9 http://ports.ubuntu.com/ubuntu-ports bionic InRelease                                                
Hit:10 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease                                       
Hit:11 https://cli.github.com/packages bionic InRelease                                                    
Hit:12 http://packages.microsoft.com/repos/code stable InRelease                                           
Hit:13 http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease                                     
Get:14 https://repo.download.nvidia.com/jetson/common r32.6 InRelease [2,555 B]                           
Hit:16 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease                
Get:17 https://repo.download.nvidia.com/jetson/t210 r32.6 InRelease [2,547 B]
Fetched 5,102 B in 3s (1,742 B/s)                                
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-smbus is already the newest version (4.0-2).
python3-pil is already the newest version (5.1.0-1ubuntu0.7).
python3-pip is already the newest version (9.0.1-2.3~ubuntu1.18.04.5).
The following packages were automatically installed and are no longer required:
  apt-clone archdetect-deb bogl-bterm busybox-static cryptsetup-bin dpkg-repack gir1.2-timezonemap-1.0
  gir1.2-xkl-1.0 grub-common kde-window-manager kinit kio kpackagetool5 kwayland-data kwin-common
  kwin-data kwin-x11 libdebian-installer4 libkdecorations2-5v5 libkdecorations2private5v5
  libkf5activities5 libkf5attica5 libkf5completion-data libkf5completion5 libkf5declarative-data
  libkf5declarative5 libkf5doctools5 libkf5globalaccel-data libkf5globalaccel5 libkf5globalaccelprivate5
  libkf5idletime5 libkf5jobwidgets-data libkf5jobwidgets5 libkf5kcmutils-data libkf5kcmutils5
  libkf5kiocore5 libkf5kiontlm5 libkf5kiowidgets5 libkf5newstuff-data libkf5newstuff5 libkf5newstuffcore5
  libkf5package-data libkf5package5 libkf5plasma5 libkf5quickaddons5 libkf5solid5 libkf5solid5-data
  libkf5sonnet5-data libkf5sonnetcore5 libkf5sonnetui5 libkf5textwidgets-data libkf5textwidgets5
  libkf5waylandclient5 libkf5waylandserver5 libkf5xmlgui-bin libkf5xmlgui-data libkf5xmlgui5
  libkscreenlocker5 libkwin4-effect-builtins1 libkwineffects11 libkwinglutils11 libkwinxrenderutils11
  libqgsttools-p1 libqt5designer5 libqt5help5 libqt5multimedia5 libqt5multimedia5-plugins
  libqt5multimediaquick-p5 libqt5multimediawidgets5 libqt5opengl5 libqt5quickwidgets5 libqt5sql5
  libqt5test5 libxcb-composite0 libxcb-cursor0 libxcb-damage0 os-prober python3-dbus.mainloop.pyqt5
  python3-icu python3-pam python3-pyqt5 python3-pyqt5.qtsvg python3-pyqt5.qtwebkit
  qml-module-org-kde-kquickcontrolsaddons qml-module-qtmultimedia qml-module-qtquick2 rdate tasksel
  tasksel-data
Use 'sudo apt autoremove' to remove them.
0 to upgrade, 0 to newly install, 0 to remove and 185 not to upgrade.
WARNING: The directory '/home/tim/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Requirement already satisfied: flask in /usr/local/lib/python3.6/dist-packages (2.0.1)
Requirement already satisfied: Jinja2>=3.0 in /home/tim/.local/lib/python3.6/site-packages (from flask) (3.0.1)
Requirement already satisfied: click>=7.1.2 in /usr/local/lib/python3.6/dist-packages (from flask) (8.0.1)
Requirement already satisfied: itsdangerous>=2.0 in /usr/local/lib/python3.6/dist-packages (from flask) (2.0.1)
Requirement already satisfied: Werkzeug>=2.0 in /usr/local/lib/python3.6/dist-packages (from flask) (2.0.1)
Requirement already satisfied: importlib-metadata in /home/tim/.local/lib/python3.6/site-packages (from click>=7.1.2->flask) (4.6.4)
Requirement already satisfied: MarkupSafe>=2.0 in /home/tim/.local/lib/python3.6/site-packages (from Jinja2>=3.0->flask) (2.0.1)
Requirement already satisfied: dataclasses in /usr/local/lib/python3.6/dist-packages (from Werkzeug>=2.0->flask) (0.8)
Requirement already satisfied: typing-extensions>=3.6.4 in /home/tim/.local/lib/python3.6/site-packages (from importlib-metadata->click>=7.1.2->flask) (3.10.0.0)
Requirement already satisfied: zipp>=0.5 in /home/tim/.local/lib/python3.6/site-packages (from importlib-metadata->click>=7.1.2->flask) (3.5.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
running install
running bdist_egg
running egg_info
writing ups_display.egg-info/PKG-INFO
writing dependency_links to ups_display.egg-info/dependency_links.txt
writing requirements to ups_display.egg-info/requires.txt
writing top-level names to ups_display.egg-info/top_level.txt
reading manifest file 'ups_display.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'ups_display.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-aarch64/egg
running install_lib
running build_py
creating build/bdist.linux-aarch64/egg
creating build/bdist.linux-aarch64/egg/ups_display
copying build/lib/ups_display/create_display_service.py -> build/bdist.linux-aarch64/egg/ups_display
copying build/lib/ups_display/ina219.py -> build/bdist.linux-aarch64/egg/ups_display
copying build/lib/ups_display/utils.py -> build/bdist.linux-aarch64/egg/ups_display
copying build/lib/ups_display/__init__.py -> build/bdist.linux-aarch64/egg/ups_display
copying build/lib/ups_display/display_server.py -> build/bdist.linux-aarch64/egg/ups_display
byte-compiling build/bdist.linux-aarch64/egg/ups_display/create_display_service.py to create_display_service.cpython-36.pyc
byte-compiling build/bdist.linux-aarch64/egg/ups_display/ina219.py to ina219.cpython-36.pyc
byte-compiling build/bdist.linux-aarch64/egg/ups_display/utils.py to utils.cpython-36.pyc
byte-compiling build/bdist.linux-aarch64/egg/ups_display/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-aarch64/egg/ups_display/display_server.py to display_server.cpython-36.pyc
creating build/bdist.linux-aarch64/egg/EGG-INFO
copying ups_display.egg-info/PKG-INFO -> build/bdist.linux-aarch64/egg/EGG-INFO
copying ups_display.egg-info/SOURCES.txt -> build/bdist.linux-aarch64/egg/EGG-INFO
copying ups_display.egg-info/dependency_links.txt -> build/bdist.linux-aarch64/egg/EGG-INFO
copying ups_display.egg-info/requires.txt -> build/bdist.linux-aarch64/egg/EGG-INFO
copying ups_display.egg-info/top_level.txt -> build/bdist.linux-aarch64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/ups_display-0.0.0-py3.6.egg' and adding 'build/bdist.linux-aarch64/egg' to it
removing 'build/bdist.linux-aarch64/egg' (and everything under it)
Processing ups_display-0.0.0-py3.6.egg
Removing /usr/local/lib/python3.6/dist-packages/ups_display-0.0.0-py3.6.egg
Copying ups_display-0.0.0-py3.6.egg to /usr/local/lib/python3.6/dist-packages
ups-display 0.0.0 is already the active version in easy-install.pth

Installed /usr/local/lib/python3.6/dist-packages/ups_display-0.0.0-py3.6.egg
Processing dependencies for ups-display==0.0.0
Searching for Adafruit-SSD1306==1.6.2
Best match: Adafruit-SSD1306 1.6.2
Processing Adafruit_SSD1306-1.6.2-py3.6.egg
Adafruit-SSD1306 1.6.2 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/dist-packages/Adafruit_SSD1306-1.6.2-py3.6.egg
Searching for Adafruit-GPIO==1.0.4
Best match: Adafruit-GPIO 1.0.4
Processing Adafruit_GPIO-1.0.4-py3.6.egg
Adafruit-GPIO 1.0.4 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/dist-packages/Adafruit_GPIO-1.0.4-py3.6.egg
Searching for spidev==3.5
Best match: spidev 3.5
Processing spidev-3.5-py3.6-linux-aarch64.egg
spidev 3.5 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/dist-packages/spidev-3.5-py3.6-linux-aarch64.egg
Searching for Adafruit-PureIO==1.1.9
Best match: Adafruit-PureIO 1.1.9
Processing Adafruit_PureIO-1.1.9-py3.6.egg
Adafruit-PureIO 1.1.9 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/dist-packages/Adafruit_PureIO-1.1.9-py3.6.egg
Finished processing dependencies for ups-display==0.0.0

And then running:
`python3 -m ups_display.ina219^C`

Gives

> Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/ups_display-0.0.0-py3.6.egg/ups_display/ina219.py", line 194, in <module>
    ina219 = INA219(addr=0x42)
  File "/usr/local/lib/python3.6/dist-packages/ups_display-0.0.0-py3.6.egg/ups_display/ina219.py", line 68, in __init__
    self.set_calibration_32V_2A()
  File "/usr/local/lib/python3.6/dist-packages/ups_display-0.0.0-py3.6.egg/ups_display/ina219.py", line 151, in set_calibration_32V_2A
    self.write(_REG_CALIBRATION,self._cal_value)
  File "/usr/local/lib/python3.6/dist-packages/ups_display-0.0.0-py3.6.egg/ups_display/ina219.py", line 78, in write
    self.bus.write_i2c_block_data(self.addr,address,temp)
TimeoutError: [Errno 110] Connection timed out

Any help would be appreciated - we have four of these battery packs and this would be very useful

**Comment by mohsen-azimi** [comment]
Same problem!
