### ISSUE TITLE
Error2 File or Directory Not Found - 6-0040 Waveshare UPS Power Module

### ISSUE THREAD

**Issue by p44-Joe** [waveshare/UPS-Power-Module#6]
Hello,

I have a Jetson Nano Developer Kit 2G (3USB + 1 USBC) with Jetpack Version: 4.6.1-b110 loaded.

I’ve updated and upgraded all the drivers from the Jetson Nano image (ubuntu 18.04) and I’m trying to run the ups software that comes with the Waveshare UPS Power Module.  hi

When I run the display_server.py I get the following error from the [utils.py](https://github.com/waveshare/UPS-Power-Module/blob/4b599ea18aa7cf33e1834f65a3e8d0461d3766b3/ups_display/utils.py#L62) import.

 ```
* Serving Flask app 'display_server' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://192.168.7.224:8000/ (Press CTRL+C to quit)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "display_server.py", line 79, in _run_display_stats
    power_watts = '%.1f' % power_usage()
  File "/home/joe/Code/UPS-Power-Module/ups_display/utils.py", line 62, in power_usage
    with open("/sys/devices/50000000.host1x/546c0000.i2c/i2c-6/6-0040/iio:device0/in_power0_input", 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/sys/devices/50000000.host1x/546c0000.i2c/i2c-6/6-0040/iio:device0/in_power0_input'
```
Running the following:

`sudo cat /sys/bus/i2c/drivers/ina3221x/6-0040/iio:device0/in_voltage0_input` results in

`cat: '/sys/bus/i2c/drivers/ina3221x/6-0040/iio:device0/in_voltage0_input': No such file or directory`

This is the directory that is missing the folder `6-0040`

```
drwxr-xr-x 5 root root    0 May 15 21:02 ./
drwxr-xr-x 4 root root    0 May 15 21:12 ../
drwxr-xr-x 3 root root    0 May 15 21:01 6-0010/
-rw-r--r-- 1 root root 4096 May 15 21:12 bus_clk_rate
--w------- 1 root root 4096 May 15 21:12 delete_device
lrwxrwxrwx 1 root root    0 May 15 21:12 device -> ../../546c0000.i2c/
drwxr-xr-x 3 root root    0 May 15 21:12 i2c-dev/
-r--r--r-- 1 root root 4096 May 15 21:12 name
--w------- 1 root root 4096 May 15 21:12 new_device
lrwxrwxrwx 1 root root    0 May 15 21:12 of_node -> '../../../../firmware/devicetree/base/host1x/i2c@546c0000'/
drwxr-xr-x 2 root root    0 May 15 21:12 power/
lrwxrwxrwx 1 root root    0 May 15 21:12 subsystem -> ../../../../bus/i2c/
-rw-r--r-- 1 root root 4096 May 15 21:12 uevent
```

**Comment by p44-Joe** [comment]
Hi! Any feedback on this?

**Comment by radfordwill** [comment]
#1 

I had an issue with the provided examples. I can't remember well but I used a virtual environment and the permissions couldn't be changed to run in it.

**Comment by p44-Joe** [comment]
I dug into the code and found that the folder 6-0040 was missing. I have also learned that things in the sys folder are markers, not files. So it appears that the hardware is no longer properly configured. I suspect it's the adafruit drivers but I'm not sure which one is used for the ina-3221x driver. I did see a post that the ina-3221x driver has been deprecated (it was experimental) and replaced with the official ina3221 driver here: https://review.lineageos.org/c/LineageOS/android_hardware_nvidia_platform_t210_jetson/+/330070 

My hardware still has the folder at `/sys/bus/i2c/drivers/ina3221x/` tho. I'm not sure where to hunt this down. I guess I could rewrite the method to use the same polling as the ina219.py script.

**Comment by p44-Joe** [comment]
BTW, by disabling the method in the utils.py I got the server to work. 

```
def power_usage():
    """Gets the Jetson's current power usage in Watts
    
    Returns:
        float: The current power usage in Watts.
    """
    #with open("/sys/devices/50000000.host1x/546c0000.i2c/i2c-6/6-0040/iio:device0/in_power0_input", 'r') as f:
    #    return float(f.read()) / 1000.0
    return 0
```

Now Usage just shows a 0

**Comment by xralphack** [comment]
Same issue!

**Comment by p44-Joe** [comment]
SO it turns out that the Jetson Nanos with 2GB don't have the chip this code needs. The hack above gets you almost all of the functionality. Just not the Power-usage.

**Comment by bowyern** [comment]
I ran into this error with a 4gb Nano. I fixed it by changing the systemd script to run as root.
