### ISSUE TITLE
TimoutError: [Errrno 110] Connection timed out

### ISSUE THREAD

**Issue by nkwasey** [waveshare/UPS-Power-Module#7]
Using power module on jetson nano.
After setup, I get this message when I run "python3 -m ups_display.ina219"

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/XXX/UPS-Power-Module/ups_display/ina219.py", line 194, in <module>
    ina219 = INA219(addr=0x42)
  File "/home/XXX/UPS-Power-Module/ups_display/ina219.py", line 68, in __init__
    self.set_calibration_32V_2A()
  File "/home/XXX/UPS-Power-Module/ups_display/ina219.py", line 151, in set_calibration_32V_2A
    self.write(_REG_CALIBRATION,self._cal_value)
  File "/home/XXX/UPS-Power-Module/ups_display/ina219.py", line 78, in write
    self.bus.write_i2c_block_data(self.addr,address,temp)
TimeoutError: [Errno 110] Connection timed out

**Comment by mohsen-azimi** [comment]
Same Problem, it does not work!
